### ISSUE TITLE
Custom `~ / (...)` urls are not handled in mail templates

### ISSUE THREAD

**Issue by djalfe** [burningice2866/CompositeC1Contrib.Email#2]

**Comment by burningice2866** [comment]
This is due to the new system for registering and converting custom url introduced in C1 5.0 requires an explicit call to ``InternalUrls.ConvertInternalUrlsToPublic`  which replaces the existing two calls here https://github.com/burningice2866/CompositeC1Contrib.Email/blob/master/Email/MailMessageBuilder.cs#L138-L139.

This also means that the minimum version of C1 for the Email package will be bumped to 5.0.

**Comment by burningice2866** [comment]
Added in commit https://github.com/burningice2866/CompositeC1Contrib.Email/commit/38951517579a1f4a3a4f631613d1a92e4b29e26b
